# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    MAKEFILE                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: wding-ha <wding-ha@student.42kl.edu.my>    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/03/12 18:02:33 by wding-ha          #+#    #+#              #
#    Updated: 2022/03/17 18:39:31 by wding-ha         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SRCS			= push_swap.c stack_function.c find_median.c
OBJS			= $(SRCS:.c=.o)
CC				= gcc
LIBS			= ./libft/libft.a
RM				= rm -f
CFLAGS			= -Wall -Wextra -Werror
LIBFT			= -make -C libft
